version=${project.version}
buildtime=${timestamp}
builder=${env.USERNAME}
builderName=${hostfile.build.user.name}
builderEmail=${hostfile.build.user.email}
buildhost=${env.COMPUTERNAME}
buildOs=${os.name}
gitBranch=${hostfile.branch}
gitCommitIdDescribe=${hostfile.commit.id.describe}
gitCommitId=${hostfile.commit.id.full}
gitCommitUrl=${hostfile.remote.origin.url}
gitCommitTime=${hostfile.commit.time}
gitDirty=${hostfile.dirty}